trigger:
- prd
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: devSodexo

steps:
- script: |
    echo "Printing environment variables..."
    echo "BRANCH_NAME: $(BRANCH_NAME)"
    echo "REPO_URL: $(REPO_URL)"
    echo "GITHUB_PAT is set"  # No imprimir el valor para mantener la seguridad
    echo "FOLDER_PROJECT: $(FOLDER_PROJECT)"
  displayName: 'Print environment variables'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    port: 25536
    runOptions: inline
    inline: |
      echo "Setting up Git global configuration..."
      if [ -z "$(git config --global user.name)" ]; then
        git config --global user.name "$(GIT_USERNAME)"
      fi
      if [ -z "$(git config --global user.email)" ]; then
        git config --global user.email "$(GIT_EMAIL)"
      fi

      echo "Cloning repository and switching to branch..."
      mkdir -p ~/project/$(FOLDER_PROJECT)
      cd ~/project/$(FOLDER_PROJECT)
      if [ ! -d .git ]; then
        echo "Cloning repository for the first time..."
        git clone https://$(GITHUB_PAT)@$(REPO_URL) .
        git checkout $(BRANCH_NAME)
      else
        echo "Repository already cloned, checking status..."
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        if [ "$current_branch" != "$(BRANCH_NAME)" ]; then
          echo "Switching to branch $(BRANCH_NAME)..."
          git fetch origin || true
          git checkout $(BRANCH_NAME) || true
        else
          echo "Already on branch $(BRANCH_NAME), pulling latest changes..."
          git pull origin $(BRANCH_NAME) || true
        fi
      fi
      echo "Branch is already up to date, continuing..."
  displayName: 'Clone GitHub repository and pull latest changes'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    port: 25536
    runOptions: inline
    inline: |
      sudo apt-get update
      sudo apt-get install -y build-essential
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      echo "Using Node.js v18.20.3..."
      nvm use 18.20.3
      echo "Installing dependencies..."
      cd ~/project/$(FOLDER_PROJECT)
      npm install || { echo "npm install failed, aborting."; exit 1; }
  displayName: 'Install npm dependencies'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    port: 25536
    runOptions: inline
    inline: |
      echo "Starting application to verify it runs correctly..."
      cd ~/project/$(FOLDER_PROJECT)
      npm start &
      sleep 10
      if ! pgrep -f "npm start"; then
        echo "Application did not start correctly, aborting."
        exit 1
      fi
      echo "Application started successfully, stopping it..."
      pkill -f "npm start"
  displayName: 'Start application to verify'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    port: 25536
    runOptions: inline
    inline: |
      echo "Building the project..."
      cd ~/project/$(FOLDER_PROJECT)
      npm run build
  displayName: 'Build the project'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    port: 25536
    runOptions: inline
    inline: |
      echo "Creating directory /var/www/html/sodexo if it does not exist..."
      sudo mkdir -p /var/www/html/sodexo
      sudo chown $(whoami):$(whoami) /var/www/html/sodexo
      echo "Cleaning up old files..."
      sudo rm -rf /var/www/html/sodexo/*
      echo "Copying built files to /var/www/html/sodexo..."
      sudo cp -r ~/project/$(FOLDER_PROJECT)/build/* /var/www/html/sodexo/
  displayName: 'Copy built files to destination'
