trigger:
- prd
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 'v18.20.3'
  displayName: 'Install Node.js'

- script: |
    ls -al $(Build.SourcesDirectory)
    npm install
    npm run build
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'npm install and build'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    script: |
      mkdir -p /var/www/html/sodexo
      chmod -R 777 /var/www/html/sodexo
      ls -al /var/www/html
  displayName: 'Create target directory and set permissions'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'server qa'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/var/www/html/sodexo'
    cleanTargetFolder: true
  displayName: 'Copy Files to /var/www/html/sodexo'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    script: |
      ls -al /var/www/html/sodexo
      cd /var/www/html/sodexo
      npm install
      npm start
  displayName: 'Install Dependencies and Start Application on Server'
