trigger:
- prd
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 'v18.20.3'
  displayName: 'Install Node.js'

- script: |
    echo "Getting public IP address..."
    curl -s http://ifconfig.me
  displayName: 'Get Public IP Address'

- script: |
    echo "Listing files in the build sources directory:"
    ls -al $(Build.SourcesDirectory)
  displayName: 'List files for debugging'
  
- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      echo "Connection successful"
  displayName: 'Verify SSH Connection'

- script: |
    echo "Installing dependencies and building the project..."
    npm install
    npm run build
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Build Project'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'server qa'
    sourceFolder: '$(Build.SourcesDirectory)/build'
    contents: '**'
    targetFolder: '/var/www/html/sodexo'
    cleanTargetFolder: true
  displayName: 'Copy Files to /var/www/html/sodexo'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      echo "Starting application..."
      cd /var/www/html/sodexo
      npm install
      npm start
  displayName: 'Start Application on Server'
