trigger:
- prd
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      echo "Creating directory /var/www/html/sodexo if it does not exist..."
      sudo mkdir -p /var/www/html/sodexo
      sudo chown $(whoami):$(whoami) /var/www/html/sodexo
      echo "Listing files in the directory:"
      ls -al /var/www/html/sodexo
  displayName: 'Create directory if it does not exist'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'server qa'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/var/www/html/sodexo'
    cleanTargetFolder: true
  displayName: 'Copy Files to /var/www/html/sodexo'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      echo "Installing dependencies and building the project..."
      cd /var/www/html/sodexo
      npm install
      npm run build
  displayName: 'Build Project'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      echo "Starting application..."
      cd /var/www/html/sodexo
      npm start
  displayName: 'Start Application on Server'
