trigger:
- prd
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 'v18.20.3'
  displayName: 'Install Node.js'

- script: |
    echo "Listing files in the build sources directory:"
    ls -al $(Build.SourcesDirectory)
  displayName: 'List files for debugging'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      echo "Creating target directory and setting permissions..."
      mkdir -p /var/www/html/sodexo
      chmod -R 777 /var/www/html/sodexo
      ls -al /var/www/html
  displayName: 'Create target directory and set permissions'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'server qa'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/var/www/html/sodexo'
    cleanTargetFolder: true
  displayName: 'Copy Files to /var/www/html/sodexo'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      echo "Installing dependencies and building application..."
      cd /var/www/html/sodexo
      npm install
      npm run build
  displayName: 'Install Dependencies and Build Application on Server'

- task: SSH@0
  inputs:
    sshEndpoint: 'server qa'
    runOptions: inline
    inline: |
      echo "Starting application..."
      cd /var/www/html/sodexo
      npm start
  displayName: 'Start Application on Server'
